name: "test-workflow"

on: workflow_dispatch

env: 
  ENV_NAME: test-env

jobs: 
  checkout_job:
    runs-on: self-hosted
    steps:  
    - name: Checkout
      uses: actions/checkout@v5.0.0
      
  terraform-installation:
    runs-on: self-hosted
    steps:  
    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
        version: latest 
          



           
    


