name: "test-workflow"

on: workflow_dispatch

env: 
  ENV_NAME: test-env
  
permissions:
  id-token: write
  contents: read
  
jobs: 
  checkout_job:
    runs-on: self-hosted
    steps:  
    - name: Checkout
      uses: actions/checkout@v5.0.0
      
  terraform-installation:
    runs-on: self-hosted
    steps:  
    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
        version: latest 

  azure-login:
    runs-on: self-hosted
    steps:  
    - name: Azure Login
      uses: Azure/login@v2.3.0    
      with:
        client-id: 5e766ae6-ac1f-4f5e-a47c-42d6536f2352
        # client-id: ${{secrets.clientid}}
        tenant-id: d55ca9e2-2a3f-46a9-ba3c-3f6d6eae23ab
        subscription-id: f47677a8-89c6-4bf2-b96b-8bbcdd5fb6d9
        
  terraform_init:
    runs-on: self-hosted
    steps:
    - name: Terraform Init
      id: init
      run: terraform init -input=false
      
  terraform_plan:
    runs-on: self-hosted
    steps:
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      continue-on-error: true

  terraform_Apply:
    runs-on: self-hosted
    steps:
    - name: Terraform Apply
      id: Apply
      run: terraform apply -input=false -auto-approve
  
    
    

           
    


